// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_AUDIO_H
#define UI_AUDIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Audio
extern void ui_Audio_screen_init(void);
extern void ui_Audio_screen_destroy(void);
extern lv_obj_t * ui_Audio;
extern lv_obj_t * ui_AudioCover;
extern lv_obj_t * ui_AudioSongLabel;
extern lv_obj_t * ui_AudioSongerLabel;
extern lv_obj_t * ui_AudioPlayBar;
extern lv_obj_t * ui_AudioCurrentTimeLabel;
extern lv_obj_t * ui_AudioTotalTimeLabel;
extern void ui_event_AudioPlaylistButton(lv_event_t * e);
extern lv_obj_t * ui_AudioPlaylistButton;
extern lv_obj_t * ui_AudioPlaylistLabel;
extern lv_obj_t * ui_AudioLRCPanel;
extern lv_obj_t * ui_AudioPlaylistPanel;
extern lv_obj_t * ui_AudioPlaylistSubPanel;
extern lv_obj_t * ui_AudioPlaylistNameLabel;
extern lv_obj_t * ui_AudioPlaylistsongerLabel;
extern lv_obj_t * ui_AudioPlaylistTimeLabel;
extern void ui_event_AudioPlayButton(lv_event_t * e);
extern lv_obj_t * ui_AudioPlayButton;
extern void ui_event_AudioPauseButton(lv_event_t * e);
extern lv_obj_t * ui_AudioPauseButton;
extern void ui_event_AudioPreButton(lv_event_t * e);
extern lv_obj_t * ui_AudioPreButton;
extern void ui_event_AudioNextButton(lv_event_t * e);
extern lv_obj_t * ui_AudioNextButton;
extern void ui_event_AudioToHomeButton(lv_event_t * e);
extern lv_obj_t * ui_AudioToHomeButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

