// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Audio = NULL;
lv_obj_t * ui_AudioCover = NULL;
lv_obj_t * ui_AudioSongLabel = NULL;
lv_obj_t * ui_AudioSongerLabel = NULL;
lv_obj_t * ui_AudioPlayBar = NULL;
lv_obj_t * ui_AudioCurrentTimeLabel = NULL;
lv_obj_t * ui_AudioTotalTimeLabel = NULL;
lv_obj_t * ui_AudioPlaylistButton = NULL;
lv_obj_t * ui_AudioPlaylistLabel = NULL;
lv_obj_t * ui_AudioLRCPanel = NULL;
lv_obj_t * ui_AudioPlaylistPanel = NULL;
lv_obj_t * ui_AudioPlaylistSubPanel = NULL;
lv_obj_t * ui_AudioPlaylistNameLabel = NULL;
lv_obj_t * ui_AudioPlaylistsongerLabel = NULL;
lv_obj_t * ui_AudioPlaylistTimeLabel = NULL;
lv_obj_t * ui_AudioPlayButton = NULL;
lv_obj_t * ui_AudioPauseButton = NULL;
lv_obj_t * ui_AudioPreButton = NULL;
lv_obj_t * ui_AudioNextButton = NULL;
lv_obj_t * ui_AudioToHomeButton = NULL;
// event funtions
void ui_event_AudioPlaylistButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_AudioPlaylistPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_AudioPlayButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AudioPlayToPause(e);
    }
}

void ui_event_AudioPauseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AudioPauseToPlay(e);
    }
}

void ui_event_AudioPreButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AudioPreMusic(e);
    }
}

void ui_event_AudioNextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AudioNextMusic(e);
    }
}

void ui_event_AudioToHomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Audio_screen_init(void)
{
    ui_Audio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Audio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Audio, &ui_img_audio_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AudioCover = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioCover, &ui_img_def_cover_png);
    lv_obj_set_width(ui_AudioCover, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioCover, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioCover, -181);
    lv_obj_set_y(ui_AudioCover, -38);
    lv_obj_set_align(ui_AudioCover, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioCover, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioCover, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioSongLabel = lv_label_create(ui_Audio);
    lv_obj_set_width(ui_AudioSongLabel, 300);
    lv_obj_set_height(ui_AudioSongLabel, 40);
    lv_obj_set_x(ui_AudioSongLabel, -178);
    lv_obj_set_y(ui_AudioSongLabel, 140);
    lv_obj_set_align(ui_AudioSongLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioSongLabel, "song");
    lv_obj_set_style_text_font(ui_AudioSongLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AudioSongerLabel = lv_label_create(ui_Audio);
    lv_obj_set_width(ui_AudioSongerLabel, 300);
    lv_obj_set_height(ui_AudioSongerLabel, 40);
    lv_obj_set_x(ui_AudioSongerLabel, -179);
    lv_obj_set_y(ui_AudioSongerLabel, 180);
    lv_obj_set_align(ui_AudioSongerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioSongerLabel, "songer");
    lv_obj_set_style_text_font(ui_AudioSongerLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AudioPlayBar = lv_bar_create(ui_Audio);
    lv_bar_set_value(ui_AudioPlayBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_AudioPlayBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AudioPlayBar, 232);
    lv_obj_set_height(ui_AudioPlayBar, 10);
    lv_obj_set_x(ui_AudioPlayBar, 155);
    lv_obj_set_y(ui_AudioPlayBar, 177);
    lv_obj_set_align(ui_AudioPlayBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_AudioPlayBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_AudioPlayBar,
                                                                                                   lv_obj_get_style_pad_right(ui_AudioPlayBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_AudioCurrentTimeLabel = lv_label_create(ui_Audio);
    lv_obj_set_width(ui_AudioCurrentTimeLabel, 50);
    lv_obj_set_height(ui_AudioCurrentTimeLabel, 18);
    lv_obj_set_x(ui_AudioCurrentTimeLabel, 2);
    lv_obj_set_y(ui_AudioCurrentTimeLabel, 179);
    lv_obj_set_align(ui_AudioCurrentTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioCurrentTimeLabel, "00:00");

    ui_AudioTotalTimeLabel = lv_label_create(ui_Audio);
    lv_obj_set_width(ui_AudioTotalTimeLabel, 50);
    lv_obj_set_height(ui_AudioTotalTimeLabel, 18);
    lv_obj_set_x(ui_AudioTotalTimeLabel, 302);
    lv_obj_set_y(ui_AudioTotalTimeLabel, 177);
    lv_obj_set_align(ui_AudioTotalTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioTotalTimeLabel, "00:00");

    ui_AudioPlaylistButton = lv_button_create(ui_Audio);
    lv_obj_set_width(ui_AudioPlaylistButton, 51);
    lv_obj_set_height(ui_AudioPlaylistButton, 23);
    lv_obj_set_x(ui_AudioPlaylistButton, 352);
    lv_obj_set_y(ui_AudioPlaylistButton, 176);
    lv_obj_set_align(ui_AudioPlaylistButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioPlaylistButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AudioPlaylistButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioPlaylistLabel = lv_label_create(ui_AudioPlaylistButton);
    lv_obj_set_width(ui_AudioPlaylistLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioPlaylistLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AudioPlaylistLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioPlaylistLabel, "list");

    ui_AudioLRCPanel = lv_obj_create(ui_Audio);
    lv_obj_set_width(ui_AudioLRCPanel, 386);
    lv_obj_set_height(ui_AudioLRCPanel, 266);
    lv_obj_set_x(ui_AudioLRCPanel, 192);
    lv_obj_set_y(ui_AudioLRCPanel, -42);
    lv_obj_set_align(ui_AudioLRCPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AudioLRCPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AudioLRCPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_AudioLRCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AudioLRCPanel, LV_SCROLLBAR_MODE_OFF);

    ui_AudioPlaylistPanel = lv_obj_create(ui_Audio);
    lv_obj_set_width(ui_AudioPlaylistPanel, 793);
    lv_obj_set_height(ui_AudioPlaylistPanel, 330);
    lv_obj_set_x(ui_AudioPlaylistPanel, 5);
    lv_obj_set_y(ui_AudioPlaylistPanel, -43);
    lv_obj_set_align(ui_AudioPlaylistPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AudioPlaylistPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AudioPlaylistPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_AudioPlaylistPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_scroll_dir(ui_AudioPlaylistPanel, LV_DIR_VER);

    ui_AudioPlaylistSubPanel = lv_obj_create(ui_AudioPlaylistPanel);
    lv_obj_set_width(ui_AudioPlaylistSubPanel, 744);
    lv_obj_set_height(ui_AudioPlaylistSubPanel, 40);
    lv_obj_set_align(ui_AudioPlaylistSubPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AudioPlaylistSubPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioPlaylistNameLabel = lv_label_create(ui_AudioPlaylistSubPanel);
    lv_obj_set_width(ui_AudioPlaylistNameLabel, 200);
    lv_obj_set_height(ui_AudioPlaylistNameLabel, 20);
    lv_obj_set_x(ui_AudioPlaylistNameLabel, -307);
    lv_obj_set_y(ui_AudioPlaylistNameLabel, 0);
    lv_obj_set_align(ui_AudioPlaylistNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioPlaylistNameLabel, "name");

    ui_AudioPlaylistsongerLabel = lv_label_create(ui_AudioPlaylistSubPanel);
    lv_obj_set_width(ui_AudioPlaylistsongerLabel, 200);
    lv_obj_set_height(ui_AudioPlaylistsongerLabel, 20);
    lv_obj_set_x(ui_AudioPlaylistsongerLabel, -22);
    lv_obj_set_y(ui_AudioPlaylistsongerLabel, 0);
    lv_obj_set_align(ui_AudioPlaylistsongerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioPlaylistsongerLabel, "songer");

    ui_AudioPlaylistTimeLabel = lv_label_create(ui_AudioPlaylistSubPanel);
    lv_obj_set_width(ui_AudioPlaylistTimeLabel, 200);
    lv_obj_set_height(ui_AudioPlaylistTimeLabel, 20);
    lv_obj_set_x(ui_AudioPlaylistTimeLabel, 211);
    lv_obj_set_y(ui_AudioPlaylistTimeLabel, 0);
    lv_obj_set_align(ui_AudioPlaylistTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioPlaylistTimeLabel, "time");

    ui_AudioPlayButton = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioPlayButton, &ui_img_play_png);
    lv_obj_set_width(ui_AudioPlayButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioPlayButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioPlayButton, 175);
    lv_obj_set_y(ui_AudioPlayButton, 143);
    lv_obj_set_align(ui_AudioPlayButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioPlayButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioPlayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioPauseButton = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioPauseButton, &ui_img_pause_png);
    lv_obj_set_width(ui_AudioPauseButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioPauseButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioPauseButton, 170);
    lv_obj_set_y(ui_AudioPauseButton, 144);
    lv_obj_set_align(ui_AudioPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioPauseButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioPauseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioPreButton = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioPreButton, &ui_img_left_png);
    lv_obj_set_width(ui_AudioPreButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioPreButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioPreButton, 130);
    lv_obj_set_y(ui_AudioPreButton, 143);
    lv_obj_set_align(ui_AudioPreButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioPreButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioPreButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_AudioPreButton, 120);

    ui_AudioNextButton = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioNextButton, &ui_img_right_png);
    lv_obj_set_width(ui_AudioNextButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioNextButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioNextButton, 227);
    lv_obj_set_y(ui_AudioNextButton, 144);
    lv_obj_set_align(ui_AudioNextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioNextButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioNextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_AudioNextButton, 120);

    ui_AudioToHomeButton = lv_image_create(ui_Audio);
    lv_image_set_src(ui_AudioToHomeButton, &ui_img_1385611356);
    lv_obj_set_width(ui_AudioToHomeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioToHomeButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioToHomeButton, -443);
    lv_obj_set_y(ui_AudioToHomeButton, -248);
    lv_obj_set_align(ui_AudioToHomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AudioToHomeButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AudioToHomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AudioPlaylistButton, ui_event_AudioPlaylistButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AudioPlayButton, ui_event_AudioPlayButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AudioPauseButton, ui_event_AudioPauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AudioPreButton, ui_event_AudioPreButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AudioNextButton, ui_event_AudioNextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AudioToHomeButton, ui_event_AudioToHomeButton, LV_EVENT_ALL, NULL);

}

void ui_Audio_screen_destroy(void)
{
    if(ui_Audio) lv_obj_del(ui_Audio);

    // NULL screen variables
    ui_Audio = NULL;
    ui_AudioCover = NULL;
    ui_AudioSongLabel = NULL;
    ui_AudioSongerLabel = NULL;
    ui_AudioPlayBar = NULL;
    ui_AudioCurrentTimeLabel = NULL;
    ui_AudioTotalTimeLabel = NULL;
    ui_AudioPlaylistButton = NULL;
    ui_AudioPlaylistLabel = NULL;
    ui_AudioLRCPanel = NULL;
    ui_AudioPlaylistPanel = NULL;
    ui_AudioPlaylistSubPanel = NULL;
    ui_AudioPlaylistNameLabel = NULL;
    ui_AudioPlaylistsongerLabel = NULL;
    ui_AudioPlaylistTimeLabel = NULL;
    ui_AudioPlayButton = NULL;
    ui_AudioPauseButton = NULL;
    ui_AudioPreButton = NULL;
    ui_AudioNextButton = NULL;
    ui_AudioToHomeButton = NULL;

}
