// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_ContainerAudio = NULL;
lv_obj_t * ui_AudioIcon = NULL;
lv_obj_t * ui_AudioLabel = NULL;
lv_obj_t * ui_ContainerBook = NULL;
lv_obj_t * ui_BookIcon = NULL;
lv_obj_t * ui_BookLabel = NULL;
lv_obj_t * ui_ContainerPhoto = NULL;
lv_obj_t * ui_PhotoIcon = NULL;
lv_obj_t * ui_PhotoLabel = NULL;
lv_obj_t * ui_ContainerVideo = NULL;
lv_obj_t * ui_VideoIcon = NULL;
lv_obj_t * ui_VideoLabel = NULL;
lv_obj_t * ui_ContainerSetup = NULL;
lv_obj_t * ui_SetupIcon = NULL;
lv_obj_t * ui_SetupLabel = NULL;
// event funtions
void ui_event_ContainerAudio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Audio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Audio_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Home, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAudio = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerAudio);
    lv_obj_set_width(ui_ContainerAudio, 64);
    lv_obj_set_height(ui_ContainerAudio, 84);
    lv_obj_set_x(ui_ContainerAudio, -320);
    lv_obj_set_y(ui_ContainerAudio, -140);
    lv_obj_set_align(ui_ContainerAudio, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerAudio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioIcon = lv_image_create(ui_ContainerAudio);
    lv_image_set_src(ui_AudioIcon, &ui_img_audio_icon_png);
    lv_obj_set_width(ui_AudioIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioIcon, 0);
    lv_obj_set_y(ui_AudioIcon, -10);
    lv_obj_set_align(ui_AudioIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AudioIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AudioLabel = lv_label_create(ui_ContainerAudio);
    lv_obj_set_width(ui_AudioLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AudioLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AudioLabel, 0);
    lv_obj_set_y(ui_AudioLabel, 30);
    lv_obj_set_align(ui_AudioLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AudioLabel, "audio");
    lv_obj_set_style_text_color(ui_AudioLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AudioLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerBook = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerBook);
    lv_obj_set_width(ui_ContainerBook, 64);
    lv_obj_set_height(ui_ContainerBook, 84);
    lv_obj_set_x(ui_ContainerBook, -240);
    lv_obj_set_y(ui_ContainerBook, -140);
    lv_obj_set_align(ui_ContainerBook, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerBook, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BookIcon = lv_image_create(ui_ContainerBook);
    lv_image_set_src(ui_BookIcon, &ui_img_book_icon_png);
    lv_obj_set_width(ui_BookIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookIcon, 0);
    lv_obj_set_y(ui_BookIcon, -10);
    lv_obj_set_align(ui_BookIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BookIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BookLabel = lv_label_create(ui_ContainerBook);
    lv_obj_set_width(ui_BookLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BookLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BookLabel, 0);
    lv_obj_set_y(ui_BookLabel, 30);
    lv_obj_set_align(ui_BookLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BookLabel, "book");
    lv_obj_set_style_text_color(ui_BookLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BookLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPhoto = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerPhoto);
    lv_obj_set_width(ui_ContainerPhoto, 64);
    lv_obj_set_height(ui_ContainerPhoto, 84);
    lv_obj_set_x(ui_ContainerPhoto, -160);
    lv_obj_set_y(ui_ContainerPhoto, -140);
    lv_obj_set_align(ui_ContainerPhoto, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerPhoto, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PhotoIcon = lv_image_create(ui_ContainerPhoto);
    lv_image_set_src(ui_PhotoIcon, &ui_img_photo_icon_png);
    lv_obj_set_width(ui_PhotoIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PhotoIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PhotoIcon, 0);
    lv_obj_set_y(ui_PhotoIcon, -10);
    lv_obj_set_align(ui_PhotoIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PhotoIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PhotoLabel = lv_label_create(ui_ContainerPhoto);
    lv_obj_set_width(ui_PhotoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PhotoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PhotoLabel, 0);
    lv_obj_set_y(ui_PhotoLabel, 30);
    lv_obj_set_align(ui_PhotoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PhotoLabel, "photo");
    lv_obj_set_style_text_color(ui_PhotoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhotoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerVideo = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerVideo);
    lv_obj_set_width(ui_ContainerVideo, 64);
    lv_obj_set_height(ui_ContainerVideo, 84);
    lv_obj_set_x(ui_ContainerVideo, -80);
    lv_obj_set_y(ui_ContainerVideo, -140);
    lv_obj_set_align(ui_ContainerVideo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerVideo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VideoIcon = lv_image_create(ui_ContainerVideo);
    lv_image_set_src(ui_VideoIcon, &ui_img_video_icon_png);
    lv_obj_set_width(ui_VideoIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VideoIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VideoIcon, 0);
    lv_obj_set_y(ui_VideoIcon, -10);
    lv_obj_set_align(ui_VideoIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VideoIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VideoLabel = lv_label_create(ui_ContainerVideo);
    lv_obj_set_width(ui_VideoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VideoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VideoLabel, 0);
    lv_obj_set_y(ui_VideoLabel, 30);
    lv_obj_set_align(ui_VideoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VideoLabel, "video");
    lv_obj_set_style_text_color(ui_VideoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VideoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSetup = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerSetup);
    lv_obj_set_width(ui_ContainerSetup, 64);
    lv_obj_set_height(ui_ContainerSetup, 84);
    lv_obj_set_x(ui_ContainerSetup, 0);
    lv_obj_set_y(ui_ContainerSetup, -140);
    lv_obj_set_align(ui_ContainerSetup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContainerSetup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetupIcon = lv_image_create(ui_ContainerSetup);
    lv_image_set_src(ui_SetupIcon, &ui_img_setup_icon_png);
    lv_obj_set_width(ui_SetupIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupIcon, 0);
    lv_obj_set_y(ui_SetupIcon, -10);
    lv_obj_set_align(ui_SetupIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SetupIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetupLabel = lv_label_create(ui_ContainerSetup);
    lv_obj_set_width(ui_SetupLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupLabel, 0);
    lv_obj_set_y(ui_SetupLabel, 30);
    lv_obj_set_align(ui_SetupLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetupLabel, "setup");
    lv_obj_set_style_text_color(ui_SetupLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ContainerAudio, ui_event_ContainerAudio, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_ContainerAudio = NULL;
    ui_AudioIcon = NULL;
    ui_AudioLabel = NULL;
    ui_ContainerBook = NULL;
    ui_BookIcon = NULL;
    ui_BookLabel = NULL;
    ui_ContainerPhoto = NULL;
    ui_PhotoIcon = NULL;
    ui_PhotoLabel = NULL;
    ui_ContainerVideo = NULL;
    ui_VideoIcon = NULL;
    ui_VideoLabel = NULL;
    ui_ContainerSetup = NULL;
    ui_SetupIcon = NULL;
    ui_SetupLabel = NULL;

}
