// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern void ui_event_ContainerAudio(lv_event_t * e);
extern lv_obj_t * ui_ContainerAudio;
extern void ui_event_AudioIcon(lv_event_t * e);
extern lv_obj_t * ui_AudioIcon;
extern lv_obj_t * ui_AudioLabel;
extern lv_obj_t * ui_ContainerBook;
extern lv_obj_t * ui_BookIcon;
extern lv_obj_t * ui_BookLabel;
extern lv_obj_t * ui_ContainerPhoto;
extern lv_obj_t * ui_PhotoIcon;
extern lv_obj_t * ui_PhotoLabel;
extern lv_obj_t * ui_ContainerVideo;
extern lv_obj_t * ui_VideoIcon;
extern lv_obj_t * ui_VideoLabel;
extern lv_obj_t * ui_ContainerSetup;
extern lv_obj_t * ui_SetupIcon;
extern lv_obj_t * ui_SetupLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

