// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Home.h"
#include "screens/ui_Audio.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_audio_icon_png);    // assets/audio_icon.png
LV_IMG_DECLARE(ui_img_book_icon_png);    // assets/book_icon.png
LV_IMG_DECLARE(ui_img_photo_icon_png);    // assets/photo_icon.png
LV_IMG_DECLARE(ui_img_video_icon_png);    // assets/video_icon.png
LV_IMG_DECLARE(ui_img_setup_icon_png);    // assets/setup_icon.png
LV_IMG_DECLARE(ui_img_audio_background_png);    // assets/audio_background.png
LV_IMG_DECLARE(ui_img_def_cover_png);    // assets/def_cover.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/right.png
LV_IMG_DECLARE(ui_img_1385611356);    // assets/icons8-left-24.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
