// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void AudioPlayToPause(lv_event_t * e);
void AudioPauseToPlay(lv_event_t * e);
void AudioPreMusic(lv_event_t * e);
void AudioNextMusic(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
