// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

void on_track_item_clicked(lv_event_t * e)
{
	// Your code here
}

void AudioPlayToPause(lv_event_t * e)
{
	// Your code here
}

void AudioPauseToPlay(lv_event_t * e)
{
	// Your code here
}

void AudioPreMusic(lv_event_t * e)
{
	// Your code here
}

void AudioNextMusic(lv_event_t * e)
{
	// Your code here
}
