// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

#include "backend/player_logic.h"

/* NOTE: this file is regenerated by SquareLine Studio export.
 * Keep the bodies as one-line forwards into the backend so they can
 * be restored trivially after a re-export. */

void on_track_item_clicked(lv_event_t * e)
{
	intptr_t idx = (intptr_t)lv_obj_get_user_data(lv_event_get_current_target(e));
	player_logic_select((int)idx);
}

void AudioPlayToPause(lv_event_t * e)
{
	(void)e;
	player_logic_toggle_play();
}

void AudioPauseToPlay(lv_event_t * e)
{
	(void)e;
	player_logic_toggle_play();
}

void AudioPreMusic(lv_event_t * e)
{
	(void)e;
	player_logic_prev_track();
}

void AudioNextMusic(lv_event_t * e)
{
	(void)e;
	player_logic_next_track();
}
